### PR TITLE
Adds support to open and save sources of 'aar' files.

### PR DESCRIPTION
**Pull request by jrobichaud**
I was often renaming '.aar' files to '.jar' in order to open them with JD-GUI.
This pull requests adds support of this file format (http://tools.android.com/tech-docs/new-build-system/aar-format).

You can test this on Facebook SDK distribution '.aar' files: https://developers.facebook.com/docs/android/
- ./facebook/facebook-android-sdk-4.12.1.aar
- ./AccountKit/account-kit-sdk-4.12.1.aar
- ./AudienceNetwork/bin/AudienceNetwork.aar
- ./AudienceNetwork/bin/DebugSettings.aar

Thanks.

### CODE REVIEW

**Comment by derFunk** [comment]
You just added support to actually open it, but it won't decompile the compiled classes which are in the .aar Android archive, or am I missing something?
E.g. I don't see any code which extracts and opens the classes.jar in JD-GUI et cetera.

**Comment by jrobichaud** [comment]
It inherits from "ZipFileLoaderProvider" like the "Jar" implementation. AAR and JAR are very similar.

**Comment by derFunk** [comment]
I see, thanks! I was using an old version of JD-Gui before, updated, and now I'm getting your point.
Imho, LGTM, should be merged ;)

**Comment by GabLeRoux** [comment]
@emmanue1 bump, I think this is not maintained anymore (no commits merged in 2 years). I think this should still get merged ;)

**Comment by emmanue1** [comment]
Done.

**Comment by jrobichaud** [comment]
Was this closed without being merged? 🤔

**Comment by GabLeRoux** [comment]
yes indeed 😱I don't see all your changes [in here](https://github.com/java-decompiler/jd-gui/search?q=aar&unscoped_q=aar) @emmanue1

**Comment by emmanue1** [comment]
Take a look to the proposed files https://github.com/java-decompiler/jd-gui/commit/cb8de5579ddc1dad1d0d6420736266818a160338 and my commit https://github.com/java-decompiler/jd-gui/commit/b4b8ec881f5c73cea1bad0f57146afefa537849d.

**Pull request closed without merging**
